CREATE TABLE IF NOT EXISTS  SLA_LOG(
id VARCHAR(60),
appName VARCHAR(60),
expectedStartTime BIGINT,
expectedEndTime BIGINT,
actualStartTime BIGINT,
actualEndTime BIGINT,
expectedDuration BIGINT,
actualDuration BIGINT ,
nominalTime BIGINT,
parentId VARCHAR(60),
appType VARCHAR(60),
`user` VARCHAR(60),
msgType VARCHAR(15),
eventStatus VARCHAR(15),
notificationMessage VARCHAR(512),
upstreamApps VARCHAR(128),
slaStatus VARCHAR(60),
LOADTIME       TIMESTAMP default CURRENT_TIME,
PRIMARY KEY (id,eventStatus)
);